### ISSUE TITLE
Monitor connection fails

### ISSUE THREAD

**Issue by gnehcoul** [TransluceAI/observatory#5]
I tried Monitor successfully at [Transluce Monitor](https://monitor.transluce.org/dashboard/chat) a few days ago. But now I fail. The page shows the connection problem. I'm not sure whether this is my problem. And maybe is something wrong with your server?
![connection](https://github.com/user-attachments/assets/944a361c-014e-452f-b68f-cf8b3ddeff13)

**Comment by kmeng01** [comment]
Thanks for reporting! Working on a fix...

**Comment by kmeng01** [comment]
We recently patched the issue; thanks for the heads up!
